layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: https://www.linkedin.com/in/hengkai-tan-a31b88272/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://stormy-cheese-458.notion.site/Hengkai-Tan-22a9b6e0b5bb801782edc3771ff3ba37
  github: https://github.com/thkkk/
  # youtube: your_username

topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: OI & Math
  
  - name: Reinforcement Learning
  
  - name: Embodied AI

  # - name: Tianshou (Deep RL Library)
  #   web_url: https://github.com/thu-ml/tianshou
  #   image_url: https://raw.githubusercontent.com/thu-ml/tianshou/master/docs/_static/images/tianshou-logo.png

  # - name: PyTorch
  #   web_url: https://pytorch.org/
  #   image_url: https://raw.githubusercontent.com/pytorch/pytorch/master/docs/source/_static/img/pytorch-logo-dark.png

theme: jekyll-theme-architect
